### ISSUE TITLE
Pushing Into An Array?

### ISSUE THREAD

**Issue by DZuz14** [gURLmeetsCode/portfolio_nkelly#2]
In MyModal.js, what is the purpose of pushing all our your HTML into an array inside your render statement?

**Comment by gURLmeetsCode** [comment]
At the time, It was the only way I could get elements to show up on the page. If you see room for improvement, please let me know.  Check out the site, it may help to understand what I was trying to accomplish. https://portfolio-natashakelly.herokuapp.com/

**Comment by gURLmeetsCode** [comment]
Im also trying to figure out how I can make changes to the code without messing up the deployment configuration. I ran into issues with the heroku buildpack for node.js and the webpack postinstall script.

**Comment by DZuz14** [comment]
I can take a look at this issue for you when traveling on the train tomorrow. What issues are you running into exactly. Any error messages or any more info you can give me?

**Comment by gURLmeetsCode** [comment]
So after I completed the application I ran the postinstall which compressed the file. Afterwards, I had to remove the script call in package.json so that the heroku build pack would successfully deploy the site. When I attempted to make changes to the projects components and push the updates -- the site did not reflect the change. Unfortunately, it did not give an error message, i just assumed it was related to the postinstall configuration and the build pack. I was curious to see if you had any experience with this...

**Comment by DZuz14** [comment]
Yeah I can fix it. Are you using heroku cli, or do you just have your repo linked so heroku can detect any updates to your code?

**Comment by gURLmeetsCode** [comment]
Sweet! I am using the heroic cli (tool belt)

**Comment by DZuz14** [comment]
Okay, so here is the problem. The postinstall flag isn't the problem. The postinstall flag is actually what bundles all of your current js, sass files together and creates an updated version of it and dumps it into your "dist" folder. When I originally made this, I clearly did not know what I was doing, as the flag should instead be changed to something like "build" instead. This flag needs to be executed anytime you make changes to your code, and have deemed its ready to be shipped to production.

For example, I forked a copy of your site, cloned it to my computer and made some changes to package.json, like so:

```
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "node server.js",
    "dev": "webpack-dev-server --hot --inline",
    "build": "webpack -p --config webpack.prod.config.js"
  }
```

I went into your Welcome component, and slightly changed some text. I then ran, this in my console,

`npm run build`

So what that did, is updated my bundle.js in the dist folder to reflect the changes I made. From there, I commited it to Heroku, and indeed can see the updated text. Here is the link to the version of your site I created on Heroku to test out my updates. 

https://nkellz.herokuapp.com/

You can see I changed the text to, "Hello There".

**Comment by DZuz14** [comment]
Also, quick tip.  If you go into your Heroku dashboard under the Activity tab, you can see your deployments being processed as they happen, and previous deployment logs. That way, if there is an error, you can check your logs and it should tell you where it went wrong.

![heroku-activity](https://user-images.githubusercontent.com/19492185/29074168-4738a1c6-7c1c-11e7-9a6f-3e3af40163a0.png)
